version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

registries:
  gradle-plugin-repository:
    type: maven-repository
    url: https://plugins.gradle.org/m2/
